---
- name: Get ca cert from local file
  hosts: ovirt_nodes:ovirt_engine
  roles:
    - ovirt_fluentd/read_local_ca_cert

- name: Configure Fluentd for oVirt
  hosts: ovirt_nodes:ovirt_engine
  roles:
    - ovirt_fluentd/client
    - ovirt_fluentd/http_input

- name: Configure Fluentd for oVirt hosts
  hosts: ovirt_nodes
  roles:
    - ovirt_fluentd/ovirt_host

- name: Configure Fluentd for oVirt engine
  hosts: ovirt_engine
  roles:
    - ovirt_fluentd/ovirt_engine

- name: Configure CollectD
  hosts: ovirt_nodes:ovirt_engine
  roles:
    - collectd
    - ovirt_collectd/write_http

- name: Configure CollectD for oVirt hosts
  hosts: ovirt_nodes
  roles:
    - ovirt_collectd/ovirt_host
    - ovirt_collectd/read_statsd

- name: Configure CollectD for oVirt engine
  hosts: ovirt_engine
  roles:
    - ovirt_collectd/ovirt_engine

- name: Create firewall rules
  hosts: ovirt_nodes
  roles:
    - firewall/commit

