---
- name: Configure Metrics
  hosts: ovirt_nodes:ovirt_engine
  tags:
    - configure
  roles:
    - validate_ovirt_env_name
    - fluentd
    - collectd

- name: Manage metrics related services
  hosts: ovirt_nodes:ovirt_engine
  tags:
    - manage_services

  roles:
    - manage_services
