---
# Address of the fluentd server host.
fluentd_fluentd_host: localhost

fluentd_keepalive: 300

# Metrics buffer configurations

fluentd_buffer_chunk_limit_metrics: 1m

fluentd_flush_interval_metrics: 10s

fluentd_buffer_queue_limit_metrics: 8

fluentd_buffer_queue_full_action_metrics: drop_oldest_chunk

fluentd_retry_wait_metrics: 1s

fluentd_retry_limit_metrics: 17

fluentd_disable_retry_limit_metrics: false

fluentd_max_retry_wait_metrics: 300s

fluentd_flush_at_shutdown_metrics: true

fluentd_num_threads_metrics: 1

fluentd_slow_flush_log_threshold_metrics: 20.0



# Logs buffer configurations

fluentd_buffer_chunk_limit_logs: 4m

fluentd_flush_interval_logs: 10s

fluentd_buffer_queue_limit_logs: 8

fluentd_buffer_queue_full_action_logs: exception

fluentd_retry_wait_logs: 1s

fluentd_retry_limit_logs: 17

fluentd_disable_retry_limit_logs: true

fluentd_max_retry_wait_logs: 300s

fluentd_flush_at_shutdown_logs: true

fluentd_num_threads_logs: 1

fluentd_slow_flush_log_threshold_logs: 20.0
