---
# name of the collectd package.
collectd_package_name: collectd

# a list of additional packages to install (presumably ones that
# provide collectd plugins).
collectd_common_plugin_packages:
  - collectd-disk
  - collectd-write_http
