---
- name: Install collectd package and plugins
  package:
    name: '{{ item }}'
    state: present
  with_flattened:
    - '{{ collectd_package_name }}'
    - '{{ collectd_common_plugin_packages }}'
    - '{{ collectd_host_plugin_packages }}'
  when: manage_packages|default(false)
  notify: restart collectd
